# Generated by Django 6.0.4 on 2026-04-08 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/Identifier for this number set', max_length=200)),
                ('numbers', models.JSONField(default=list, help_text='Array of numbers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('sum_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mean_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('median_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('std_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variance_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('range_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('q1_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('q3_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.numberset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
